// Builds the icon font from src/icons/svg.
//
// 1. Outlines strokes into fills (font glyphs can only be filled shapes).
// 2. Runs Fantasticon to produce a single woff2 font.
// 3. Emits a typed icon list (TS) and a glyph map (SCSS) so the CSS classes
//    and the <Icon> component stay in sync with the font.
//
// Codepoints are persisted in src/icons/codepoints.json so existing icons keep
// the same glyph when new icons are added (safe for cached fonts).
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SVGFixer from 'oslllo-svg-fixer';
import { generateFonts, FontAssetType } from 'fantasticon';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'src/icons/svg');
const outlinedDir = path.join(root, 'node_modules/.cache/yv-icons-outlined');
const genDir = path.join(root, 'src/icons/generated');
const fontDir = path.join(root, 'src/fonts');
const codepointsFile = path.join(root, 'src/icons/codepoints.json');

const FONT_NAME = 'yv-icons';
const FIRST_CODEPOINT = 0xf101;

await rm(outlinedDir, { recursive: true, force: true });
await mkdir(outlinedDir, { recursive: true });
await mkdir(genDir, { recursive: true });
await mkdir(fontDir, { recursive: true });

// svg-fixer globs its input, so it needs forward slashes on Windows.
const posix = (p) => p.split(path.sep).join('/');
await SVGFixer(posix(srcDir), posix(outlinedDir), { traceResolution: 1200 }).fix();

const names = (await readdir(srcDir))
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.slice(0, -4))
  .sort();

// Keep previously assigned codepoints; append new icons after the highest one.
const saved = existsSync(codepointsFile)
  ? JSON.parse(await readFile(codepointsFile, 'utf8'))
  : {};
const codepoints = {};
let next = Math.max(FIRST_CODEPOINT - 1, ...Object.values(saved)) + 1;
for (const name of names) {
  codepoints[name] = saved[name] ?? next++;
}

await generateFonts({
  name: FONT_NAME,
  inputDir: outlinedDir,
  outputDir: fontDir,
  fontTypes: [FontAssetType.WOFF2],
  assetTypes: [],
  codepoints,
  // Every source icon shares the same 20×20 box with built-in padding;
  // normalizing would strip that padding and make glyph sizes inconsistent.
  normalize: false,
  fontHeight: 1000,
  descent: 0,
});

await writeFile(codepointsFile, JSON.stringify(codepoints, null, 2) + '\n');

const banner = '// Generated by scripts/build-icons.mjs — do not edit.\n';

await writeFile(
  path.join(genDir, 'icon-names.ts'),
  banner +
    `export const iconNames = ${JSON.stringify(names, null, 2)} as const;\n\n` +
    'export type IconName = (typeof iconNames)[number];\n',
);

await writeFile(
  path.join(genDir, '_glyphs.scss'),
  banner +
    '$glyphs: (\n' +
    names.map((n) => `  '${n}': '\\${codepoints[n].toString(16)}',`).join('\n') +
    '\n);\n',
);

console.log(`Built ${FONT_NAME}.woff2 with ${names.length} icons.`);
